name: deployment
on: push
jobs:
  Lint:
    name: Lint Command
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v6
      - name: Install Node
        uses: actions/setup-node@v6
        with:  
          node-vesion: 18
      - name: Execute Node
        run: npm ci
      - name: Execute lint
        uses: sibiraj-s/action-eslint@v4
      - name: Execute lint script
        run: npm run lint