name: Print Issue
on: issues
jobs:
  Print_Issue_Info:
      name: Print Issue Info
      runs-on: ubuntu-latest
      steps:
        - name: Print Info
          run: echo ${{ toJSON(github.event.issue) }}
